wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.13
    cli_version: 0.17.6
    framework: huggingface
    huggingface_version: 4.47.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1759549844
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 71
      - 83
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 71
      - 83
      3:
      - 13
      - 23
      4: 3.11.13
      5: 0.17.6
      6: 4.47.0
      8:
      - 5
      13: linux-x86_64
output_dir:
  desc: null
  value: your_path/reg_xlarge_dinov2_base_align_4_cls
exp_name:
  desc: null
  value: linear-dinov2-b-enc4
logging_dir:
  desc: null
  value: logs
report_to:
  desc: null
  value: wandb
sampling_steps:
  desc: null
  value: 10000
resume_step:
  desc: null
  value: 0
model:
  desc: null
  value: SiT-B/2
num_classes:
  desc: null
  value: 1000
encoder_depth:
  desc: null
  value: 8
fused_attn:
  desc: null
  value: true
qk_norm:
  desc: null
  value: false
ops_head:
  desc: null
  value: 16
siglip_drop_prob:
  desc: null
  value: 0.1
data_dir:
  desc: null
  value: /mnt/nvme-fast/datasets
resolution:
  desc: null
  value: 256
batch_size:
  desc: null
  value: 256
allow_tf32:
  desc: null
  value: true
mixed_precision:
  desc: null
  value: fp16
epochs:
  desc: null
  value: 1400
max_train_steps:
  desc: null
  value: 1000000
checkpointing_steps:
  desc: null
  value: 10000
gradient_accumulation_steps:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_weight_decay:
  desc: null
  value: 0.0
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
seed:
  desc: null
  value: 0
num_workers:
  desc: null
  value: 4
path_type:
  desc: null
  value: linear
prediction:
  desc: null
  value: v
cfg_prob:
  desc: null
  value: 0.1
enc_type:
  desc: null
  value: dinov2-vit-b
proj_coeff:
  desc: null
  value: 0.5
weighting:
  desc: null
  value: uniform
legacy:
  desc: null
  value: false
cls:
  desc: null
  value: 0.03
